---
version: "3"
services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        logging:
            driver: none

    kafka-1:
        image: wurstmeister/kafka
        container_name: kafka-1
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092,HOST://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:39092,HOST://localhost:9092
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        logging:
            driver: none

    uploader-service:
        image: madhavsikka99/flam-uploader
        container_name: uploader-service
        ports:
            - 8080:8080
        volumes:
            - common-storage:/usr/src/data

    processor-service:
        image: madhavsikka99/flam-processor
        container_name: processor-service
        ports:
            - 8090:8090
        volumes:
            - common-storage:/usr/src/data

    status-checker-service:
        image: madhavsikka99/flam-status-checker
        container_name: status-checker
        ports:
            - 8085:8085
        volumes:
            - common-storage:/usr/src/data

volumes:
    common-storage:
        external: true